package com.thinking.machines.chessFramework.common;
public enum UserAction{
NEW_USER_LOGIN,
LIST_OF_ONLINE_USERS,
HAVE_ANY_INVITATION,
INVITE_USER,
INVITATION_ACCEPTED,
INVITATION_REJECTED,
AS_INVITATION_ACCEPTED_OR_NOT,
PLAY_GAME,
TERMINATE_GAME
};